name: simdutf-is-genuine

on:
  - push
  - pull_request

jobs:
  simdutf-is-genuine:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6

      - name: Check if vendored simdutf is genuine
        run: |
          cd simdutf
          curl -L https://github.com/simdutf/simdutf/releases/download/v8.0.0/singleheader.zip -O
          unzip -o singleheader.zip
          git diff --exit-code
